weight_file: "ckpt_jrdb_ann_ft_dr_spaam_e20.pth" # name of the weight file
detector_model: "DR-SPAAM"  # Set model name: DROW3 or DR-SPAAM
use_gpu: True     # Set to True to use GPU
conf_thresh: 0.5  # Set confidence threshold
stride: 1         # Downsample scans for faster inference
panoramic_scan: False  # Set to True if the scan covers 360 degree
detect_mode: True  # Set to True to enable detection
